(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(0,0,0,0)","#000000"],[0.529,1],-17.7,-10,0,-17.7,-10,73.2).s().p("AAfH0IgjAAIgBAAIgUAAIAAgBIgCAAIgFAAIgCAAQgHAAgEgCIgBAAIgBgBIgBAAIgBAAIgBAAQgMAAgHgDIgCAAIgDAAIgBgBQgGABgFgDIgBAAQgKAAgGgCIgBAAIgBAAIgBAAQgGgBgFgDIgBAAIgBgBIgCAAQgLgBgHgEIgCAAIgPgGIgBAAQgIgBgFgDIgBgBQgDAAgCgCQgLgCgIgEQhWglg/g9Qg/g8gphTQgphTgKhyIAAgBIAAgsIAAgBIAAgMIABAAIAAgBIAAgLQAOhvAthPQArhQBCg5QBCg6BZgiQBCgYBSgHIAxAAIABAAQAHADAKgCIACAAIALABIAAABQBsAPBOAsQBQAtA5BCQA6BCAhBZQAMAfAIAiQAHAcADAfIABACIABAZIAAABIABAAIAAANIAAACIAAAPIAAACIAAAVIAAACIgBAAQgDAugJAnQgaBig1BHQgDAIgEAFQg3BGhKAwQhLAwhmAWIgBAAIg+AIIAAABIgBAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(-50,-50,100,100), null);


(lib.sun = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#FFFF00","rgba(255,255,0,0)"],[0.596,0.945],0,0,0,0,0,5.6).s().p("AgkAlQgPgQABgVQgBgUAPgQQAQgPAUABQAVgBAQAPQAPAQgBAUQABAVgPAQQgQAPgVgBQgUABgQgPg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// glow
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["#FFFFFF","rgba(0,0,0,0)"],[0.596,0.945],0,0,0,0,0,9).s().p("Ag6A6QgYgYAAgiQAAghAYgZQAZgYAhAAQAiAAAYAYQAZAZAAAhQAAAigZAYQgYAZgiAAQghAAgZgZg");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Layer 2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["#FFFFFF","rgba(0,0,0,0)"],[0.596,0.945],0,0,0,0,0,1.3).s().p("AhHAJQgegEABgFQgBgEAegDQAegEApAAQAqAAAeAEQAdADAAAEQAAAFgdAEQgeADgqAAQgpAAgegDg");
	this.shape_2.setTransform(0.2,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.rf(["#FFFFFF","rgba(0,0,0,0)"],[0.596,0.945],0,0,0,0,0,1.3).s().p("AgIBIQgDgeAAgqQAAgpADgeQAEgeAEAAQAFAAADAeQAEAeAAApQAAAqgEAeQgDAdgFABQgEgBgEgdg");
	this.shape_3.setTransform(0.2,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["#FFFFFF","rgba(0,0,0,0)"],[0.596,0.945],0,1.5,0,0,1.5,1.3).s().p("AgKAzIgBgkQAAglADgcIARAAQADAcAAAlIgBAkg");
	this.shape_4.setTransform(0.2,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.sun, new cjs.Rectangle(-10,-10,20.3,20.3), null);


(lib.juno_animated = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#996666").ss(1,1,1,3,true).p("AACihIAGATIAGAUIAFATIAGATIBYgmAhQhpIgGgTIBYglIBZglIAFATIAGATIAGATIAFATIAGATIAGATIhZAmIAGATIAFATIAGASIAGATIAFATIAGATIAGATIAFATIAGATIAAABIhYAlIAAgBIgGgTIgFgTIgGgTIgGgTIgFgTIgGgTIgGgTIgFgTIgGgSIgFgTIgGgTIgGgTIBYglIBZgmAhKhVIgGgUIBYglIBYglAijgwIgBgEQgDgIgCgHIBZgmAidgdQgCgGgCgFIAAgCIgCgGIBZglIBYglIBYgmAiSAIIgEgNIgCgFIgFgTIBYglIgFgTAiMAcIgGgUIBZgkIBYglIAFATIhYAlgAiYgKIBZglIBYglIAGATIBYgmAiBBBQgCgGgCgFIgCgIIBZglIBYgkIBYgmIAGAUIAGASIAFATIAGASIAFATIhYAmIhYAlIhZAmQgBgGgCgGIgCgHIgGgUIgFgSgAhlCgIgGgSAhaDGIgFgSIgGgUAgBCiIhZAlIAAgBAgdBCIhZAlAh7BVIBYgmIBYglIBZglAgMB7IhZAlAgHCOIhYAmAgYBVIhYAmAgBChIhZAlAiphDIgFgTIBYgmAgpAcIhYAlAiHAuIgFgSACIgtIhZAlIhYAkACTgIIhYAlIhYAlAB9hUIAFATACkAwIAGAUIAFASIAAABIhYAmACvBWIhYAmIhYAlACkAwIhYAmIhYAlACqBEIhZAlIhYAlACZAKIhZAmIhYAlACeAdIAGAT");
	this.shape.setTransform(37.7,-28.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666699").s().p("AAUBFIAGASIAGATIAFATIAAABgAgBgHIAFATIAFATIAGATIACAHgAgWhNIAEANIAGATIAFATIACAIgAgkh9IABAFIACAFg");
	this.shape_1.setTransform(24.9,-21.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#669999").s().p("AhaDGIBZglIAAAAIhZAmgAhfCzIBYglIhYAlIgGgTIBZglIhZAlIgGgSIBZgmIhZAmIgDgMIgCgHIBYgmIBYglIAGATIAGATIAFATIAGATIhYAlIBYglIAAAAIhYAlIAAAAIgGgTIBYglIhYAlIgFgTIBYglIhYAlIgGgTIBYglIhYAlIgGgTIAGATIAGATIAFATIAGATIhZAlgAgBChgAgHCOgABXB8IBYglIAAAAIhYAlgABXB8IgGgTIBZglIhZAlIgFgTIBYglIhYAlIgGgTIgGgTIBZgmIhZAmIgFgTIBYglIhYAlIAFATIhYAlIgFgTIBYglIhYAlIhZAmIgFgTIBYgmIhYAmIgGgUIBYglIBYgkIAGASIAGATIgGgTIBZglIAFATIAGASIAFATIhYAmIBYgmIAGAUIAGATIAFATIhYAlgAgdBCIgGgTIBYglIhYAlIgGgTIAGATgAhwB7IgGgTIBZgmIAFATIhYAmgABRBpgAgSBogACvBXgAgdBCgAiBBBIgEgLIgCgIIBZglIAFATIhYAlgAiMAbIBYgkIhYAkIgGgTIBZgkIAFATIAGASIhZAlgAgpAcIgFgTIBYgkIhYAkIgGgSIBYglIhYAlIgFgTIBYglIAFATIgFgTIBYglIhYAlIgGgTIBYglIhYAlIAGATIhYAlIgGgTIBYglIhYAlIhZAlIgFgSIBYgmIhYAmIgEgMIAAgCIgCgFIBZgmIAFATIAGATIgGgTIBYglIhYAlIgFgTIBYglIhYAlIgGgUIBYglIhYAlIAGAUIhZAmIgBgFIgFgPIBZgmIgGgTIAGATIhZAmIgFgTIBYgmIBYglIAGATIAGAUIAFATIAGATIgGgTIBZgmIhZAmIgFgTIBYgmIhYAmIgGgUIBYglIhYAlIgGgTIBZglIAFATIAGATIAGATIAFAUIAGATIAGATIhZAlIAGATIAFATIhYAkgAA1AKIgGgSIBZgmIhZAmIgFgTIBYglIhYAlIgGgTIBZglIAFATIAGASIAGATIhZAlgAguAJgAiSAIIgEgMIgCgGIBZglIAGATIhZAkgAAvgIgAg0gJgAAqgbgAg/gvgAAfhBgAAfhBgAAThngAhQhpgAAOh6gAAIiOg");
	this.shape_2.setTransform(37.7,-28.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#996666").ss(1,1,1,3,true).p("ABmigIAFATIAGATIAGATIAFATIhZAmIhXAlIgGgTIgFgTIgGgTIBXglIAGATIBZgmAhLhVIgFgTIgGgTIBYglIBZgmIAFATIAGATAACigIAFATIAGATIAFATIBZgmAAHiNIBZgmAhQhoIBXglAhLhVIBYglIBZgmAAehBIAFATIAGATIAGATIAFASIAGATIhYAlIgFgTIgGgTIgGgTIgFgSIhYAkIgBAAIgFgTIgGgSIgGgTIgFgTIgGgTIgFgTIBYglAgNB7IhYAlIgGgTIgGgTIgFgTIgGgTIgFgTIgGgTIgGgTAgSBoIgGgTIgGgTIhYAlIAAAAAgNB7IgFgTIhZAlAgCChIgFgTIgGgTAgBCiIgBgBIhYAlIAAAAIgGgTIgFgTABQBpIAGATIAAAAIhXAmIhZAlIAAgBAA/AwIAGATIAGATIAFATIhXAlIhYAlIgBAAAA/AwIhXAlIhYAlIgBAAAg6gcIBYglIBZgmAAvgIIhYAkIhYAlAgvAJIBYgkIBZgmIAGATIAFATIAGATIAFASIAGATIAGATIAFATIAGATIAAABIhZAlAgjAvIBXglIBZglABLBWIhYAlABWB8IhYAlABFBDIhXAlAA6AdIAFATAg/gvIBXglIAGATAhFhCIgGgTACvBWIhZAmACkAwIhZAmACpBDIhZAmACeAdIhZAmACYAKIhZAmACTgIIhZAlACIguIhZAmAB8hUIAGATAijgwIAAAAIBYglAiegdIABAAIBYglAiHAuIAAAAIBYglAiphDIBZglAiYgKIBZglAh8BUIBZglAiSAIIBYgk");
	this.shape_3.setTransform(10.3,-17.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#669999").s().p("AhaDGIAAAAIBYglIABABIhZAlgAhaDGIgGgTIABAAIBYglIhYAlIgBAAIgFgTIgGgTIBZglIhZAlIgGgTIABAAIBYglIhYAlIgBAAIgFgTIAAAAIBYglIAGATIAGATIAFATIhYAlIBYglIAGATIAFATIhYAlgAgCChIBYglIhYAlIgFgTIBXglIgFgTIBZgmIhZAmIgGgTIBZgmIhZAmIgGgTIBZgmIhZAmIgFgTIBZglIhZAlIAFATIhXAlIgGgTIBYglIgGgTIBZglIhZAlIgFgSIBZgmIhZAmIgGgTIBZgmIhZAmIgGgTIBZgmIAGATIAGATIAFATIAGATIAFASIAGATIAGATIAFATIAGATIAAABIhZAlIAAAAIBZgmIhZAmIgGgTIBZgmIhZAmIAGATIAAAAIhXAmgAgCChgAgHCOgAgHCOIgGgTIBYglIAFATIhXAlgABWB8gAgNB7IgFgTIBXglIAGATIhYAlgAgNB7gABQBpgAgSBoIgGgTIBXglIAGATIhXAlgAh2BnIgGgTIBZglIhZAlIgFgTIBYglIhYAlIgGgTIAAAAIBYglIAGATIAGATIAFATIhYAlgAgeBCgAgeBCgAgjAvIBXglIAGATIhYAlgAA/AwgAgjAvIgGgTIBYgkIAFASIhXAlgAiHAuIgGgTIABAAIBYgkIhYAkIgBAAIgFgTIBYgkIhYAkIgGgSIBZglIAFATIAGATIAFASIhYAlgAgpAcIgGgTIBYgkIAGATIhYAkgAiNAbgAgvAJIgFgSIBXglIAGATIhYAkgAg6gcIBYglIAFATIhXAlgAiYgKIgGgTIABAAIBYglIAGATIhZAlgAg6gcIgFgTIBXglIAGATIhYAlgAiegdIgFgTIAAAAIBYglIAGATIhYAlgAAehBIBZgmIhZAmIgGgTIBZgmIhZAmIhXAlIgGgTIBXglIAGATIgGgTIBZgmIhZAmIgFgTIBZgmIAFATIAGATIAGATIAFATIhZAmgAijgwIAAAAIgGgTIBZglIAFATIBYglIAFATIhXAlIgGgTIhYAlgAijgwgAAehBgAhFhCgAiuhWIBYglIBYglIAFATIhXAlIgGgTIAGATIhZAlgAhQhoIBXglIAGATIhYAlgAAShngAAShngAhQhogAANh6gAAHiNIBZgmIAGATIhZAmgAAHiNgAACigIBZgmIAFATIhZAmgABgizg");
	this.shape_4.setTransform(10.3,-17.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#996666").ss(1,1,1,3,true).p("AhQhpIgFgTIBXglIAGATIAGAUIAFATIBZgmIAFATIAGATIAGATIAFATIAGATIAGATIAFATIAGASIhZAmIAGATIAGATIAFATIAGATIAAAAIhYAmIhZAlIAAgBIgFgTIgGgTIgGgSIgDgMIgCgIIgGgTIgFgTIgGgTIgEgLIgCgIIBZglIgFgSIgGgTIgGgTIgFgTIgGgTIBYglIBYgmIAGATAACihIBZglIAFATIAGATAAIiOIBYglAhQhpIBYglACTgIIhYAlIhYAlIgFgTIBXglIBZglAAvgIIhXAkIhZAlAAfhBIAFATIAGATIAFATIAGASIAGATIAFATIhXAlIgGgTIhZAlAAZhUIAGATIBYgmAgSBoIgFgTIhZAlAgMB7IgGgTIhZAmAgGCOIgGgTIhZAlABGBDIhYAlABRBpIhXAlIhZAlABMBWIhYAlAgiAvIgGgTIgGgTIBYgkIBYgmACIguIhZAmAB9hUIhZAmIhXAlIhZAlIgGgUIBZgkIBYglAidgdIgEgNIgCgGIgBgEIgFgPIgFgTIBZgmAiYgKIgFgTIBZglIBXglIAGATIBYgmAiSAIIgEgNIgCgFIBZglIBYglAiHAuIgFgSAijgwIBZglIgGgUAgBCiIAAgBIhZAlABXB8IhYAlIgFgTAh7BUIBZglAiphDIBZgmACkAwIAGAUIAFASIAAABIhYAlACeAdIAGATIhYAmACvBWIhYAmACqBEIhZAlACeAdIhYAmACZAKIAFAT");
	this.shape_5.setTransform(65.3,-40.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#666699").s().p("AAUBEIAGAUIAGATIAFATIAAAAgAgBgHIAFASIAFATIAGATIACAIgAgWhOIAEAPIAGATIAFATIACAHgAgkh9IABAEIACAGg");
	this.shape_6.setTransform(52.5,-33);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#669999").s().p("AhaDHIBZgmIAAABIhZAlgAhfC0IBZgmIAFATIhZAmgAhfC0IgGgTIBZgmIhZAmIgGgUIBZglIhZAlIgDgLIgCgIIBZglIhZAlIgGgTIBZglIhZAlIgFgTIBZglIhZAlIgGgTIBZglIgGgTIAGATIhZAlIgEgLIgCgHIBZgmIgFgSIBXglIhXAlIgGgTIBYglIhYAlIgGgTIBYglIAGATIAFATIAGATIAFATIhXAkIAGATIAFATIAGATIAFATIAGATIBYglIAFATIAGATIhYAlIgFgTIBXglIhXAlIgGgTIAGATIhZAmgAguAJIBYgkgAgBChIBYglIAAABIAAgBIgGgTIBZgmIhZAmIgFgTIBYgmIhYAmIgGgTIBYgmIhYAmIgGgTIBZglIAFASIAGATIAGATIAFATIhYAmIBYgmIAAABIhYAmIhYAlgAgBChgAgSBoIBYglIAGATIhYAlgABRBpgAgSBoIgFgTIBXglIAGATIhYAlgACvBWgABMBWgAgXBVIgGgTIBYglIAFATIhXAlgAgdBCIgFgTIBXglIAGATIhYAlgABAAwIgFgTIBYgkIhYAkIgGgTIBZgkIAFATIAGASIhZAlgAgoAcIBXgkIAGASIhXAlgAiHAvIgFgTIBZglIAFASIhZAmgAiMAcIgGgTIBZglIhZAlIgEgOIgCgEIBZgmIAGATIAGATIhZAlgAAvgIIBZglIAGATIhZAkgAAvgIIgFgTIBYgmIAGAUIhZAlgAgzgJgAidgdIBZglIAFATIhZAmgACOgagAAqgbIgGgTIBZgmIAFATIhYAmgAg5gcgAidgdIgEgNIgCgGIBZglIhZAlIgBgEIgFgPIBZgmIAGAUIBYglIAFATIgFgTIBYglIAGASIAFATIAGATIhYAmIgGgTIBYgmIhYAmIhYAlIgFgTIBXglIAGATIgGgTIBZgmIhZAmIhXAlIgGgTIAGATIhZAlgAAkguIgFgTIBYgmIAGATIhZAmgAhEhCgAiuhWIBZglIAFASIhZAmgAB9hUgAAZhUgAhQhpIBYgkIAGATIhYAlgAhQhpIgFgSIBXglIAGATIhYAkgAAIiNIBYgmIhYAmIgGgTIBZgmIAFATIAGAUIhYAlgAhVh7gAAIiNg");
	this.shape_7.setTransform(65.3,-40.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#996666").ss(1,1,1).p("AB7AAQAABCgkAuQgkAugzAAQgyAAgjguQglguAAhCQAAhAAlguQAjgvAyAAQAzAAAkAvQAkAuAABAg");
	this.shape_8.setTransform(-23.2,-6.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#669999").s().p("AhVBvQgkguAAhBQAAhAAkguQAjgvAyABQAzgBAkAvQAjAuABBAQgBBBgjAuQgkAvgzAAQgyAAgjgvg");
	this.shape_9.setTransform(-23.2,-6.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#996666").ss(1,1,1).p("AjVgLICJimIBVAAIDNBRIgNDcIjWA2IhVAAIhzi0AhMixIDNBRIgODcIjVA2ABzB8IBWAAACBhgIBVAA");
	this.shape_10.setTransform(-14.8,-5.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#669999").s().p("AhiCyIDVg2IjVA2Ihzi0IAAgJICJimIBVAAIDNBRIhVAAIjNhRIDNBRIgODcIBWAAIjWA2gABzB8IAOjcIBVAAIgNDcgACBhgg");
	this.shape_11.setTransform(-14.8,-5.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#996666").ss(1,1,1,3,true).p("AhehDIAJgSIAKgSIA2A/IAKgSIAJgSIAJgSIA2A/IgKASIgJARIg1g+Ig2g/IAJgSIAKgSIAKgSIAJgSIAKgSIAKgSIA1A/IA2A/IA2A/IgKASIgKASIgJARIgKASIgKASIgJASIgKATIgKASIgJASIgKASIgKASIgJASIg1hAIgKATIgJASIg2g/Ig2g/IAJgSIAKgSIAJgSIAKgSIAKgSIA2A/IAJgSIAKgSIA1A+IgKASIgJASIgKASIgJATIg2hAIAKgSIAKgRIA1A+IA2BAAhiBoIg2g/IgBgBAhiBoIAKgSIAJgSIAKgTIg2g+AiYApIAKgSAhPBEIg2g/AAkiUIAKgSAgIjmIABABAARhwIAJgSIA2A/IA2A/AgkivIA1A/IA2A/IgKASIA2A+AgbjBIA1A/IAKgSIA2A/IgKASIgJASIA2A+ABkhnIgKASIA2A/AgChMIA1A/IA2A+AAHheIAKgSAgRjTIA1A/AguidIA1A/Ag4iLIA2A/AADBMIg1g/Ig2g+AgGBfIgJARIg2g/IAJgSIg2g+AATDVIgKARIg1g/Ig2g/AAcDCIgJATIg1hAIgKASAAcDCIg1g/Ig2g/AAvCeIg1g/AA5CMIg2hAAAgAWIA2BAABMBoIg2hAIg1g+Ig2g/AAmCwIgKASAAqAEIgKASABgBDIg2g/AhLhnIAKgS");
	this.shape_12.setTransform(-33.9,-26.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#669999").s().p("AgtCnIAKgSIA1A/IgKASgAgjCVIAKgSIg2g/IA2A/IgKASIg2g/IA2A/IgKASIg2g/IAKgSIAKgSIAKgTIg2g+IAJgSIAKgSIAKgSIA2A/IA1A+IgKASIg1g/IAKgRIgKARIg2g+IA2A+IgKASIA2A/IgJASIAJgSIAJgSIAKgSIA2BAIgKASIg2hAIA2BAIgKASIg1hAIA1BAIgJASIg1hAIA1BAIgKASIg1g/IAKgTIg2g/IAJgSIgJASIA2A/IgKATIA1A/IgKASgAg8AfIg2g+gAgjCVgAgjCVgAANA6IAJgSIAKgSIA2BAIgKASIg2hAIA2BAIgJASgAgPBwgAhjBoIg2g/IAKgSIAKgSIAKgSIA2A+IgKATIg2g/IA2A/IgKASIg2g/IA2A/IgKASgAg8AfIAKgSIA1A/IgJASgAAgAWIAJgSIgJASIg1g+IAJgSIA1A+IAKgRIAJgSIg2g/IAKgSIAKgSIg1g/IA1A/IgKASIg1g/IAKgSIAJgSIAKgSIA1A/IgKASIAKgSIA2A/IA2A/IgKASIg2g/IA2A/IgJASIg2g/IAJgSIg2g/IgJASIA2A/IgKASIg2g/IA2A/IgKASIAKgSIA2A+IgKASIg2g+IA2A+IgJASIg2g+IA2A+IgKASIg2g/IA2A/IgJATgABZhVIAKgSgAAjiUIg1g/gAhZBWgAhPBEgAANA6Ig1g+IAJgSIAKgSIA1A+IgKASIg1g+IA1A+IgJASgAhFAxgAAWAogAAgAWgABGgxIAKgSIA2A/IgKARgAgyANgAgyANgAgMg6IAKgSIA1A/IgKARgAgogEIg2g/IAJgSIAKgSIA2A/IgKASIg2g/IA2A/IgJASgAAzgNgAgChMIAIgSIA2A/IgJASgACPgWgAgfgWgAgVgogAhLhnIAJgSIAKgSIA2A/IgKASIg2g/IA2A/IgJASgABGgxgAgMg6gAgMg6gABQhDgAAaiCIAJgSIA2A/IgJASgAgChMgAgChMgAg4iLIAJgSIAKgSIA1A/IgKASIg1g/IA1A/IgIASgABZhVgAAGhegAAaiCg");
	this.shape_13.setTransform(-33.8,-26.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#666699").s().p("AhICHICQkOIABABIgKASIgKASIgJASIgKASIgKASIgJASIgKASIgJARIgJASIgKASIgKASIgJASIgKATIgJASIgKASg");
	this.shape_14.setTransform(-42,-35.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#996666").ss(1,1,1,3,true).p("AgSjTIAKgSIA1A/AgSjTIABAAIA0A/IA3A/IgKASIgKASIA3A+IgKASIgKASAgbjBIAJgSAgbjBIAAAAIA1A/IA2A/IA2A/IgJARAglivIAKgSAgvidIABAAIA0A/IAKgSIAKgSIAJgSIAKgSIA3A/IgKASIA2A/IgKASAhLhnIAAABIA1A+IAKgSIg1g/IAAAAIAJgSIABAAIA1A/IAIgSIA2A/IgJASIgKARIgKATIgJASIgJASIgKASIg1hAIAKgRIAJgSIg2g+IAAgBIAKgSIAKgSAhehDIAJgSAgMg6IAKgSIA1A/IA2A+IgKASIgKATIgJASIgKASIgJASIgKASIgJASIgKASIg1g/Ig2g/IAKgTIAJgSIAKgSIg2g+IAKgSIA2A/IA1A/IA1A/Ag4iLIAJgSIAKgSIA1A/IA2A/IgKASIA3A+AAfAXIA2A/ABfBDIg2g/Ig1g+AhZBWIAKgSIg2g/AgPBxIgKASIgJASIgKASIg3g/IAKgSIg1g/IACgFIAHgNIAJgSIAKgSIAKgSAgGBfIgJASIg2hAIg2g9IgBgBAAWApIg1g/IAJgSIA1A/AAvCeIg1g/Ig2hAIg2g9IAAgBAAmCwIg1g/AgiCVIg3g/ABMBoIg2g/AADBNIgJASAA5CMIg2g/AhjBoIg1g/IAHgOIADgEAATDUIgKASIg1g/AATDUIg1g/AAcDCIgJASABkhnIA2A/IgKAS");
	this.shape_15.setTransform(-50.7,-45.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#666699").s().p("AACgEIgCAEIgBAFg");
	this.shape_16.setTransform(-65.1,-43.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#669999").s().p("AgsCnIg2g/IAKgSIAJgSIAKgTIAJgSIA2BAIgJASIAJgSIg2hAIAKgSIg2g+IAJgSIAKgSIAAABIA2A+Ig2g+IAAgBIAJgSIABABIA1A+Ig1g+IgBgBIAKgSIAKgSIAJgSIABAAIA0A/IgIASIAIgSIAKgSIA2A/IAKgSIA2A/IgKARIg2g+IA2A+IgKASIg2g+IAKgSIgKASIg2g/IA2A/IgJASIg1g/IA1A/IgKARIg1g+IAKgSIgKASIg1g/IgBAAIABAAIA1A/IA1A+IgKATIAKgTIA2A/IgKATIg2g/IA2A/IgJASIg2g/IAJgSIg1g/IAKgSIgKASIgJASIAJgSIA1A/IgJASIg1g/IA1A/IgKASIg1g/IAKgSIgKASIg2g/IA2A/IgJARIAJgRIA1A/IgJASIAJgSIA2A/IgJASIg2g/Ig1hAIA1BAIgJASIA1A/IgJASIg1g/Ig2hAIA2BAIgKASIg2g/IA2A/IgJASIg2g/IA2A/IgKASIAKgSIA1A/IgKASgAg4iLIA2A/Ig2g/IAAAAgAgiCVIAJgSIA1A/IgJASgAgZCDIAKgSIA1A/IgKASgAgGBfIAJgSIA2A/IgKASgAgiCVgAgZCDgAAMA7IAKgSIA2A/IgKASgAgPBxgAiYApIAHgOIADgEIACgFIAHgNIAKgSIAJgSIABABIA1A9IgJASIg2g9IAAgBIAAABIA2A9IgKATIg2g/IA2A/IgJASIg2g/IA2A/IgKASgAhYBWgAADBNgAhPBEgAApAEIAKgRIA2A+IgKASgAAMA7gAAzgNIAJgSIA2A+IgJASgAhFAxgAAWApgAg8AfgAhxgeIgBgBIAKgSIA2A+IgKASgAApAEgABQhDIAKgSIA2A/IgKASgAAzgNgAAzgNgABahVIgKASIg2g/IA2A/IgKASIg2g/Ig1g/IA1A/IgKASIg0g/IgBAAIAKgSIAKgSIAAAAIA1A/Ig1g/IAAAAIAKgSIAAAAIA1A/Ig1g/IAAAAIAKgSIA1A/IgKASIgKASIgKASIAKgSIAKgSIA2A/Ig2g/IAKgSIA2A/IgKASIAKgSIA2A/IgKASgAA8gfgABQhDgAAGheg");
	this.shape_17.setTransform(-50.7,-45.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#996666").ss(1,1,1,3,true).p("AhjBoIg2g/IAFgJQABgDACgCIACgEIADgFQAAgBABgBQADgGADgFIAJgSIAKgSIAKgSIAJgSIAKgSIAJgSIABABIA1A+IAKgSIAKgSIA1A/IgJARIgKATIgKASIgJASIA2A/IgKASIgKASIg1g/IgJASIgKASIg2g/IAJgTIg1g9IgBgBAgvidIAKgSIA1A/IAKgSIAJgSIAKgSIA3A/IA2A/IgKASIgKASIgJARAg4iLIAAAAIA2A/IAIgSIAKgSIA3A/IA2A+IgKASIgKASIgJASIgKATIgKASIg2g/Ig1g/IAJgSIA2A/IA2A/AgMg6Ig1g/IgBAAAhMhnIAKgSIAKgSIAJgSIABAAIA0A/IA3A/IgKASIA2A+AgbjBIAAAAIA1A/IA2A/IgJASIgKASIA2A+AgSjTIABAAIA0A/IA3A/IgKASIA2A/AgbjBIAJgSIAKgSIA1A/AglivIAKgSAAqAEIg2g+Ag8AfIg2g9IAAgBAgfgWIg2g+IAAgBAgyANIAJgRIA2A/IgKASIgJASIg2hAIAKgSIg2g+AhfhDIA2A/IAKgSAgiCVIg3g/IAKgSIg2g/AhjBoIAKgSIg2g/AA5CMIg2g/Ig1hAAgPBxIg3hAIAKgSAgZCDIgJASIgKASIg3g/ABahVIA2A/ABMBoIgJASABgBDIg2g/ABkhnIgKASAATDUIgKASIg1g/AAmCwIgKASIgJASIg1g/AAvCeIgJASIg1g/AAcDCIg1g/");
	this.shape_18.setTransform(-67.5,-65.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#669999").s().p("AgsCnIAKgSIA1A/IgKASgAgiCVIAJgSIg2g/IAJgTIg1g9IgBgBIABABIA1A9IgJATIg2g/IA2A/IgKASIg2g/IA2A/IgKASIg2g/IAFgJIADgFIACgEIADgFIABgCIAGgLIAJgSIAKgSIAAABIA2A9Ig2g9IAAgBIAKgSIAJgSIAKgSIAAABIA2A+Ig2g+IAAgBIAJgSIABABIA1A+Ig1g+IgBgBIAKgSIAKgSIAJgSIAKgSIAKgSIAJgSIABAAIA0A/Ig0g/IgBAAIAKgSIA1A/IgKASIAKgSIA3A/IA2A/IgKASIg2g/IAKgSIgKASIA2A/IgKASIg2g/Ig2g/IA2A/IgJASIg3g/IA3A/IgKASIg3g/IAKgSIAKgSIAJgSIgJASIgKASIg1g/IA1A/IgKASIgIASIg2g/IAAAAIAAAAIA2A/IgKASIg1g/IgBAAIABAAIA1A/IgKASIA2A/IAKgTIAJgRIA2A+IgJASIg2g/IA2A/IgKATIg2g/IgKASIA2A/IgJASIg2g/IAJgSIg1g/IAJgSIgJASIgKASIg2g/IA2A/IgJARIAJgRIA2A/IgKASIg1hAIg2g+IA2A+IgKASIgKASIAKgSIA2BAIgJASIg3hAIA3BAIgKASIAKgSIAJgSIg2hAIAKgSIA1BAIgJASIAJgSIAKgSIg2g/IAKgSIA1A/IgJASIA2A/IgKASIg2g/IA2A/IgKASIg1g/IA1A/IgJASIg1g/IA1A/IgKASIg1g/IA1A/IgJASgABQhDIAKgSIg3g/IA3A/gAguidIA0A/Ig0g/IgBAAgAgbjBIA1A/Ig1g/IAAAAIAAAAgAgsCnIg3g/IAKgSIAKgSIA2A/IgJASIg3g/IA3A/IgKASgAgPBxgAAWApIAKgSIA2A/IgKASgAhZBWgAADBNgAhPBEgAAzgNIg1g/IAIgSIA3A/IgKASIAKgSIA2A+IgKASgAAWApgAA9gfIAKgSIA2A+IgKASgAgWgoIAKgSIA2A+IgKATgABHgxIAJgSIA2A/IgJARgAgyANgAAqAEgAgMg6IAKgSIA1A/IgJARgAgpgEgAAzgNgACQgWgAA9gfgAA9gfgAgMg6gABQhDgAgChMgAAQhwg");
	this.shape_19.setTransform(-67.5,-65.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#666699").s().p("AACgEIgCAEIgBAFg");
	this.shape_20.setTransform(-81.8,-63.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#996666").ss(1,1,1,3,true).p("AAFh6IASAIIgJBPIATAJIATAIIATAIIATAIIATAHIATAIIgJBQIgTgIIgTgIIgJBPIgTgIIgTgIIgTgIIAJhQIgTgIIgIBPIgTgIIgTgIIgTgIIgTgIIgTgIIgTgIIgTgJIgSgIIgBAAIAJhOIAJhQIABAAIATAIIAJhPIATAIIATAIIASAIIAUAJIATAIgAiAizIABAAIATAIAiAizIAAgBAh1hcIATAJIAJhQAiJhkIAJhPAiIhkIAJhPAhZADIAKhOIAJhQAhZADIgTgHIgSgIIgTgIIgBAAAgWgzIATAIIARAIIgJBPIgRgIIgUgIIgSgIIgTgJIAJhOIASAIIAUAIIgKBPIgJBPAgMAkIAJhPIAIhPAgyAUIAIhPIAKhPAh+gMIAJhQAhsgEIAKhPIATAIIATAIIAIhQAiRgUIAJhQAhFALIgUgIAgNiCIgJBPAAqhqIATAIIATAIIgJBQIgJBOIgTgIIgJBQABjhRIATAIIgJBOIgJBQIgJBPABjhRIgJBPIgJBPIgTgJIgJBQACcg5IgJBPIgJBPIgJBQIgTgJIgTgIIgTgIACJhBIgJBOIATAJACcg5IAAAAACJhBIATAIAA9hiIgJBQIgJBOIgTgIIAJhOIAJhQAB2hJIATAIABQhaIATAJAAXhyIATAIAB3BdIgJBPACKBlIgTgIAAPCEIgSgJAhiBTIAJhQAgWBzIAKhPAg8BjIAKhPAhPBbIAKhQAiaA6IAJhOAiIBCIAKhOAh1BLIAJhP");
	this.shape_21.setTransform(-22.8,45.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#669999").s().p("ABuCsIAJhQIATAJIgJBPgABuCsIgTgIIAJhQIATAIIgJBQgABbCkIgTgIIAJhPIATAHIgJBQgABICcIgUgJIAKhPIAJhOIgJBOIgTgIIAJhOIgJBOIATAIIgKBPIgTgHIAKhQIgTgIIATAIIgKBQIgTgIIAKhQIAJhPIATAJIATAIIgTgIIAJhQIgJBQIgTgJIAJhPIgJBPIgTgIIgJBPIATAIIgKBQIgSgJIAJhPIgSgJIAJhOIgJBOIgTgIIATAIIgJBQIgTgIIAJhQIgJBQIgTgIIAKhQIgKBQIgTgJIAKhPIATAIIASAIIAJhOIATAIIASAIIgSgIIgTgIIAJhQIgJBQIgSgIIAJhPIgJBPIgTgJIAJhPIgJBPIgJBPIgTgIIAJhOIgJBOIgTgHIATAHIgKBPIgTgIIAKhOIgKBOIgTgIIAKhOIgKBOIgTgIIAKhOIATAIIATAIIAJhPIATAIIATAHIgTgHIAJhQIgJBQIgTgIIAJhQIgJBQIgTgJIATAJIgJBPIgTgIIAJhQIgJBQIgTgIIAJhQIgJBQIgBAAIABAAIgKBOIAAAAIAJhOIAJhQIAJhQIABAAIATAJIgJBPIgTgIIAJhQIgJBQIgBAAIABAAIATAIIAJhPIATAIIATAIIATAIIATAJIASAHIASAIIgIBQIAIhQIATAIIgJBQIAJhQIATAJIATAIIATAIIgJBQIATAIIATAHIgTgHIAJhPIATAIIATAIIgJBOIATAIIgTgIIAJhOIATAIIgJBOIgJBQIgTgJIAJhPIgJBPIgTgIIAJhPIATAIIgTgIIgJBPIgTgHIAJhPIgJBPIgTgJIATAJIgJBPgABtAFIAJhOgAgEB7IgSgIIAJhQIASAJIgJBPgAhPBaIgTgIIAKhPIATAIIgKBPgABRBNgAAYA0gAAYA0IgTgIIAJhPIATAIIgJBPgAAFAsgAgyATIAJhOIASAIIgJBOgAgyATIgTgIIAJhPIATAJIgJBOgAhFALgAhYADgABagCIgTgIIAJhQIATAJIgJBPgAiRgUgAAhgbgAAhgbgAAhgbgAiIhkg");
	this.shape_22.setTransform(-22.8,45.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#666699").s().p("AB7A1IgTgIIgTgIIgTgJIgTgHIgTgIIgTgJIgRgHIgTgIIgTgIIgTgJIgTgIIgTgIIgTgIIgTgIIAAAAIAAgBIEbB6IAAAAg");
	this.shape_23.setTransform(-21.5,33.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f().s("#996666").ss(1,1,1,3,true).p("AA9hiIATAIIAAAAIgJBPIATAJIATAHIATAIIATAIIgJBQIgTgJIgTgIIgJBQIgTgIIgTgIIgTgIIgTgIIAJhQIgTgJIgIBQIgTgIIgTgIIgTgIIgTgIIgTgIIgTgIIgSgJIgTgIIgBAAIAJhPIAJhPIAJhQIABAAIATAIIASAJIATAIIATAIIATAIIATAIIgJBQIgJBOIgJBQAAXhzIATAJIATAIIgJBPIATAIIgJBPIgJBQAAXhzIAAABIgJBPIATAIIATAIIgJBPIgTgIIAJhPIAJhPAgEgrIAIhPIAAgBIATAIABjhSIgJBQIgJBOIgTgIIgTgIIgJBQAB2hKIAAABIgJBOIgJBPIgTgIIgJBQAB2hKIATAIIAAABIgJBOIgJBPIgJBQACJhCIATAJIgJBOABjhSIATAIABQhaIATAIAg9hEIAJhPIAAAAAiIhkIAJhPIAAgBAh1hcIAJhPIAAgBAiIhkIATAIIASAIIATAIIATAIIATAJIATAIIATAIIASAIIgJBOIgSgIIgTgIIgTgIIgTgIIgTgIIAJhPIAJhPAiJhkIABAAAh+gNIgTgIIgBAAAhsgEIgSgJIAJhPAgNAjIAJhOAgzATIAJhOIAJhQAhGALIAJhPAiRgVIAJhPAhsgEIAJhQIAJhPAhZADIgTgHACKBlIgJBQIgTgJIgTgIAiHBCIAJhPAiaA6IAJhPAgWBzIAJhQAAPCEIgSgJAhiBTIAJhQAhPBbIAJhQAg8BjIAJhQAh1BLIAJhPAgOiDIASAI");
	this.shape_24.setTransform(-20,20.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#669999").s().p("ABuCsIAJhQIgTgIIAJhPIATAIIATAIIgJBQIgTgJIAJhPIgJBPIATAJIgJBQgABuCsIgTgIIAJhQIATAIIgJBQgABICcIAJhQIATAIIgJBQgABICcIgTgIIAJhQIATAIIgJBQgAA1CUIgTgIIAJhQIgTgIIAJhPIgJBPIATAIIgJBQIgTgIIAJhQIgTgJIAJhOIATAIIATAIIATAIIgTgIIAJhPIgJBPIgTgIIgTgIIAJhPIAAgBIAAABIgJBPIgSgIIASAIIgJBOIATAJIgJBQIgSgJIAIhQIgSgIIAJhOIgTgIIAJhQIASAIIAAABIgIBPIAIhPIAAgBIATAIIATAJIgJBPIAJhPIATAIIATAIIAAAAIgJBPIATAJIATAHIgTgHIAJhQIATAIIAAABIgJBOIAJhOIAAgBIATAIIAAABIgJBOIAJhOIAAgBIATAJIgJBOIgTgIIgTgIIgJBPIgTgIIAJhOIgJBOIgTgIIAJhPIgJBPIgTgIIAJhPIgJBPIATAIIgJBQgAgDB7IgTgIIAJhQIgJBQIgTgIIAJhQIgJBQIgTgIIAJhQIgJBQIgTgIIAJhQIgJBQIgTgIIAJhQIgJBQIgTgIIAJhPIATAHIgTgHIAJhQIgJBQIgSgJIASAJIgJBPIgSgJIAJhPIgJBPIgTgIIAJhPIgJBPIgBAAIAJhPIABAAIgBAAIAJhPIAJhQIABAAIATAIIASAJIATAIIATAIIAAAAIgJBPIAJhPIAAAAIATAIIATAIIgJBQIgTgIIAJhQIgJBQIgTgJIgTgIIAJhPIgJBPIgTgIIAJhPIgJBPIgSgIIAJhPIAAgBIAAABIgJBPIgTgIIATAIIgJBPIgTgIIAJhPIAJhPIAAgBIAAABIgJBPIgBAAIABAAIgJBPIATAIIAJhPIASAIIATAIIgJBPIATAIIATAIIATAIIATAIIASAIIgIBQgAB3BcgABkBUgABkBUgABRBMgAA+BEgAArA8gAAYA0gAggAbIgTgIIAJhOIATAIIgJBOIAJhOIATAIIgJBOgACTAVgAgzATIgTgIIAJhPIATAJIgJBOgAhGALIgTgIIAJhPIATAIIgJBPgABagCIgTgJIAJhPIAAAAIATAIIgJBQgAAOgjgAgXgzgAgqg7gAhQhMgABjhSgAiIhkg");
	this.shape_25.setTransform(-20,20.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("#996666").ss(1,1,1,3,true).p("AibA6IAAAAIAJhOIAJhQIABAAIATAIIAJhPIASAIIATAIIATAIIATAJIAUAIIARAIIATAIIATAIIATAIIATAIIgJBQIATAIIATAHIATAIIATAJIgJBPIgTgIIgTgIIgTgIIgTgJIgJBQIgUgIIgTgIIgRgJIgTgIIgTgIIgTgIIgTgIIgTgIIgTgIIgTgJIAKhOIgTgIIgBAAAB2hJIATAIIgJBOIgJBQIgJBPIgTgIIgUgIIgSgIABjhRIgJBPIgJBPIgKBPAB2hJIgJBOIgJBQIgJBPABjhRIATAIACcg5IAAAAIgJBPABQhaIATAJACJhBIATAIAh/izIAAgBAh/izIAAAAIATAIAiJhkIAKhPAiIhkIAJhPAhQhLIATAIIAJhQAhrgEIgTgIIAJhQIASAJIAJhQAhGALIgTgIIgSgHIAIhPIATAIIAJhQAgzAUIgTgJIAJhOIATAIIATAIIgJBPIgTgIIAJhPIAJhPAhZADIAJhOAgNAkIgTgIIgJBPAgNAkIAKhPIARAIIATAJIATAIIgJBOIgTgIIgTgIIgIBPAgXgzIAUAIIAHhPAAhgaIAJhQAAXhyIgJBPIgJBPIgSgIAgNiCIgKBPAiRgUIAJhQAAOCEIAKhQIAJhOAArA8IgKBQACKBlIgJBQIgTgJAA9hiIgJBQIATAIIgJBOIgTgIAgWBzIAJhPAg8BjIAJhPAhPBbIAJhQAhiBTIAJhQAh1BLIAKhPAibA6IAKhOAiIBCIgTgI");
	this.shape_26.setTransform(-25.7,70.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#666699").s().p("AB7A1IgTgIIgTgIIgTgIIgTgIIgTgIIgTgJIgRgHIgTgIIgTgIIgTgJIgTgIIgTgIIgTgIIgTgIIAAAAIAAAAIEbB5IAAAAg");
	this.shape_27.setTransform(-24.3,58.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#669999").s().p("ABtCsIAKhQIgKBQIgTgIIAKhPIgKBPIgSgIIAJhPIgJBPIgTgIIAJhQIATAJIATAIIATAHIATAJIgKBPgAAiCMIAJhQIgJBQIgTgIIAJhQIATAIIATAIIgJBQgAAPCEIgTgJIAJhQIgSgIIAJhOIgJBOIgTgIIATAIIgJBQIgTgIIAJhQIgJBQIgTgIIAJhQIgTgIIAJhOIATAIIgJBOIATAIIAJhOIATAIIASAIIgJBOIAJhOIATAIIgJBPIgTgJIATAJIgJBQgAgEB7IgSgIIAJhQIASAIIgJBQgAB3BcIAJhPIATAJIgJBPgAhPBaIAJhPIgJBPIgTgIIAJhPIgJBPIgTgIIAKhOIgKBOIgSgIIAJhOIATAIIgTgIIAJhQIAJhQIgJBQIgTgIIAJhQIgJBQIAAAAIAAAAIgJBQIAJhQIATAIIgJBQIgTgIIAAAAIAAAAIATAIIgJBOIgTgIIAJhOIgJBOIgBAAIAKhOIAJhQIAJhQIAAAAIATAIIATAJIASAIIATAIIATAJIgJBPIAJhPIATAIIgJBPIgTgIIATAIIgJBOIgTgIIAJhOIgTgIIAJhQIgJBQIgTgIIAJhQIgJBQIgSgIIAJhQIgJBQIgTgJIATAJIgJBPIASAHIATAIIATAIIgJBQgABkBVIAJhQIATAIIgJBPgABRBNIAJhPIgJBPIgTgJIAJhOIgTgIIgJBOIgTgIIAJhPIATAJIgTgJIAJhPIgJBPIgTgIIAJhQIATAJIATAIIgJBQIAJhQIATAIIgJBQIATAIIATAHIgTgHIAJhQIATAJIATAIIgJBOIAJhOIATAIIgJBPIgTgJIgTgIIAJhOIgJBOIgJBQgAA+BEIgTgIIAJhOIATAIIgJBOgAgzATgAhGALIgTgIIAJhOIATAIIgJBOgAhZADIgSgHIAJhPIASAIIgJBOgABagCIgTgIIAJhQIATAIIgJBQgABHgKgAAOgjIgSgIIAIhQIATAIIgJBQgAgXgzIAJhPIASAHIgIBQgAgXgzgAgXgzgAhQhLgABjhSgAhihTgAhihTgAiIhkgAAEh7g");
	this.shape_28.setTransform(-25.7,70.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-83.8,-89.4,167.7,178.8);


(lib.juno = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.juno_animated("synched",0);
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:76.9},71,cjs.Ease.linear).to({startPosition:0},25,cjs.Ease.linear).to({rotation:0},71,cjs.Ease.linear).wait(16));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-83.8,-89.4,167.7,178.8);


(lib.earth = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol1();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.16,0.16);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(100,178,57,0.957)").s().p("AAAABIAAgBIABABIgBAAg");
	this.shape.setTransform(-2.6,7.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(117,207,53,0.996)").s().p("AAAAAIAAAAIAAABg");
	this.shape_1.setTransform(-2.8,7.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#7BDA37").s().p("AAAABIAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAgBABg");
	this.shape_2.setTransform(-0.5,8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(105,188,54,0.953)").s().p("AABAAIgCAAIADAAg");
	this.shape_3.setTransform(-2.1,7.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6DC137").s().p("AAAAAIAAAAIAAAAg");
	this.shape_4.setTransform(-0.5,4.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#71C936").s().p("AgBAAIABAAIACABIgDgBg");
	this.shape_5.setTransform(-2.3,4.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#74CE35").s().p("AAAAAIABAAIgBABIAAgBg");
	this.shape_6.setTransform(-2.5,3.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#73CB36").s().p("AAAABIAAgBIAAABg");
	this.shape_7.setTransform(-2.9,3.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#72CA36").s().p("AAAAAIABAAIAAABIgBgBg");
	this.shape_8.setTransform(-2.7,4.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#75CF35").s().p("AAAAAIABAAIAAAAIgBABg");
	this.shape_9.setTransform(-4.3,0.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#78D434").s().p("AAAABIAAgBIABABg");
	this.shape_10.setTransform(-2.7,1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#75D035").s().p("AANARIACAAIAAABgAgNgPIABgCIAAACg");
	this.shape_11.setTransform(-2,3.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6FC537").s().p("AgLAUIAAgDIACADgAAHgCQgCgFgFgDQAFACAAACIADACQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAIgDgBgAAJgSIABgBIABAAIgCADg");
	this.shape_12.setTransform(-2,3.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6ABD38").s().p("AAAAAIABAAIgBABg");
	this.shape_13.setTransform(-0.2,1.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#74CE36").s().p("AAAAAIABAAIgBABg");
	this.shape_14.setTransform(0.4,1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#75CF36").s().p("AAAAAIABAAIgBABg");
	this.shape_15.setTransform(0.8,0.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#78D534").s().p("AACABIgDAAQAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAABg");
	this.shape_16.setTransform(1.6,0.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("rgba(22,45,79,0.992)").s().p("AgFALIAAgDIAAgBIAAgCIACgFQAAABABAAQAAAAAAAAQABAAAAAAQABAAAAgBIgBAAQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAgBAAAAIAEACIABAAIgBgEIABgEIABAAIAAgEIACAJIgBAAQAAAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAIgBAAIgBAAIABAFIgBAAIAAADIgCgBQAAAAgBAAQAAAAAAABQAAAAgBABQAAAAAAAAIgCAEQgBAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAgBg");
	this.shape_17.setTransform(7.4,-0.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#77D235").s().p("AgLAcIACAAIAAAAIAAABIgCgBgAALgcIABAAIAAABg");
	this.shape_18.setTransform(1,2.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#76D035").s().p("AAAAAIABAAIgBAAIAAAAg");
	this.shape_19.setTransform(0.8,-1.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6EC337").s().p("AAAAAIABAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAg");
	this.shape_20.setTransform(0.2,-2.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#77D334").s().p("AAAAAIABAAIAAAAIgBAAg");
	this.shape_21.setTransform(1.3,-2.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#73CC36").s().p("AgaASIAAgBIABAAIgBACIAAgBgAAbgSIABABIgBAAg");
	this.shape_22.setTransform(-1.6,-1.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#70C737").s().p("AgCAQIgCgFIgBgDIABgFIABAAIgEgIQgBgCABgDIgBAAQgBAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAIgCgCIAAgCQAAgBABAAQAAAAABgBQAAAAAAgBQABAAAAgBIADAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAQAAAAAAAAQAAAAAAAAQABABAAAAIACAAIAAgCIAFADIAAABIAEAHIABADIACACIgCADQgDAAgBADIgCADQAAAEACABIgFAAgAAJAHQAAAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAAAQAAAAABAAQABgBAAAAQABAAAAABQABAAAAAAIABAAIAAACQAAAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgEABQAAAAgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBg");
	this.shape_23.setTransform(3.3,-2.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#70C637").s().p("AgUAYQABAAAAAAQAAgBABAAQAAAAABABQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIABABIAAABQgEAAgCgEgAAvgVQgBABAAAAQAAABAAAAQAAAAAAAAQAAAAABAAIAAADQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBIABgEIAAgCIAAgCIABABQAAABAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAIAFAHIgCAAIgBADIgDgFgAg0gYIAAgCIACAAIgBACIgBAAg");
	this.shape_24.setTransform(1,1.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#71C836").s().p("AAeAUIAAgGQAAAAAAgBQAAAAABAAQAAAAAAAAQAAABAAAAIACAHIgDgBgAAVgHIACAAIABAAIABgFIgDgFQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQACAAADACIABAEIABABIAAACIAAABIABAEIAAACQgBAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIgCABIgGgFgAAIgEIABAAQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAABAAIAAABIgDgCgAgggDIADgEIgCAEIgBABg");
	this.shape_25.setTransform(-0.8,-1.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#6ABC38").s().p("AAAAAIABAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAABAAAAg");
	this.shape_26.setTransform(-2.6,-3.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#6BBE38").s().p("AgCACIAFgEIgFAFg");
	this.shape_27.setTransform(-2,-4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#75CE35").s().p("AAMADIAAABIgBABIABgCgAgLgEIABAAIgBABg");
	this.shape_28.setTransform(-0.4,-4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("rgba(112,199,55,0.996)").s().p("AAOBGIgFAAIgEAAQAAAAABgBQAAAAgBAAQAAAAAAAAQAAAAgBAAIAAABIgCAAIAAgBIgDAAIgCAAIgCgCIgDAAIgEgBIgBAAIgBgBIgDgBIgBAAIABgCIAAAAIABAAIACgDIgCgBQgCgHgDgFIABAAIgBgDIABgBIAAgCIADAAIADgBIABgBIACgEIAFgBIACAAIACABIABABQAAABAAAAQABAAAAAAQAAABAAAAQAAAAABAAIABAAIABABIABABIABAAIAEABIgCAAIADABQACAEAFACIAAABIACAAQACABAAAEIAAABIABABQABAAAAAAQAAABAAAAQABAAAAAAQAAAAABAAIACAAIACABIACAAIAAABIACAAIACABIAAACQgFACgDADIgCADIgKABgAgQAgIAAgBIgBgBIAAAAIgBAAIAAgBIgBgCIAAgCIAAgDIgCgEIgEgEIgCgDQAAAAAAAAQAAAAAAAAQAAgBgBAAQAAAAAAAAIgBgBIAAgBIgBgCIAAgBIgDgFIAAAAIABgBIAAgBQACgDAAgDIAAgFIABgDQAAgBgBAAQAAAAAAABQgBAAAAAAQAAABgBAAIAAADQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAgBAAIABABIgBAAIAAABIgBgFIABgDIAAgBIABgGQABAAAAABQAAAAAAgBQABAAAAAAQAAgBAAAAIgCAAIACgBIABgBIACgEIAAgBIAAgBQAFgGAGgCQABAAAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIgCAAIAAgBIACAAIABgDIABgCIAGgGIABgBIABgBIAAgFIgCgEQgBAAAAgBQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAABABAAQAAAAAAAAQABABAAAAQAAAAABAAIACgCIABgBIABAAIADABIACgBIADABIABAAIADADIAAABIgBACIAAAEIAAACIAAABIABABQABAFACADIABAAIAAgCQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIgBAAIAAgCIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAAAIABAEQAAAAAAAAQAAAAAAAAQAAABAAAAQAAABAAAAIgBACIAAABQAAABAAAAQAAABAAAAQABAAAAAAQAAAAABAAIABgCIABAAIAAACIgBABIAAABIABABIACAAIAAABIgBAAIABABIAAABIgGACQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAABIgCABIgBABIAAABIgBAAIAAABIABABIgBAAIACADIABABQABAAAAAAQAAABAAAAQAAAAAAABQAAAAgBAAQAAABAAABQAAABABAAQAAABAAAAQAAAAAAABIAAABIADgFIAAAAIACgBIgBAAIABgBIAAgBIABgBIAAgDIABgBQAEABABADIAAACQADACABADIAAABIABABIgBAAIABABQABABAAAAQAAABAAAAQAAABAAABQAAAAgBABIgBABIAAABIgCAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAAAIgBAAIgGABIACAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIABABIABABQAAABgBAAQAAAAgBAAQAAABAAAAQgBAAAAAAIAEAAIgGABIgBAAQAAgBAAAAQgBgBAAAAQgBAAAAAAQgBAAAAABIgBAAIAAABIgDABIgCAAIAAAAIgCABIgBABIAAABIgCAAIAAACIgEABQgBAAAAgBQgBAAAAAAQAAAAAAAAQAAABAAAAIgBAAIgBABIAAABIgBABIAAACQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIAAgDIAAgCIAAgBIgGgEIgBAAIgDgDIgCAAIgBAAIAAAAIgCAAIgCACIgBAAIAAABIgCACIAAABQAAAEAEADIABAAIAAgCIACAAIADAAIAAADIgEADIABACIABAAIACACIAAABQABAAAAAAQABABAAAAQAAABAAAAQgBABAAAAIgBAAIgCACIAAAAIAAACQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAABAAIABABIgBAAIADACIAAAAIAAABIgFgCg");
	this.shape_29.setTransform(-1,1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#74CD36").s().p("AgVArIAAgBIADAEIgDgDgAAVgRIABgBIgBACgAADgtIACAAIACABIgEgBg");
	this.shape_30.setTransform(-1,-1.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("rgba(112,199,54,0.996)").s().p("AATA+IAAgFQACgNAFgHIABgGIADgDIABgCIgDACQAAAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAAAIgBAAIgBgDIAAgCIABAAIgBgBIAAgCIABgBQABAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAgBIgCgDQAAgBAAgBQAAgBAAAAQABgBAAAAQAAgBAAAAIAAgDIAAgCIgBgCQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAgBQAAAAgBgBIABgHIgCgCQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgBAAQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAAAIAEAJIgBAAQgBAAAAAAQAAgBgBAAQAAAAAAABQgBAAAAAAQgCgBgCgEIAAgCIgEgJQAAAAgBgBQAAAAAAgBQAAAAAAAAQABAAAAAAIAEAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIgDgBQAAgBAAAAQgBAAAAgBQAAAAABAAQAAgBAAAAIgBgCQgBgFgEgEIgDAAQgDgDgDAAIgBAAIgFgDQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIgBAAIgDgBIgGgDIgBABIAAACQgEgBgCgBQAAAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAABQgDgBgDgBIgBADIgEAAQgEADgEgDQABAAABAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAIAAgDQAAAAABgBQAAAAAAAAQABAAAAAAQAAgBABAAIACAAIABgBIACAAIAAgCIAFAAIABAAIAAgCQAAgBAAAAQAAgBAAAAQAAAAAAAAQAAgBAAAAIAAgBIAVAGIAIAFQANAGAJALQAJAKAFAPIADAKIAAAEIgBAAIgBADIABAEIgBAAIgEgCQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIABACQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAIgCAEIAAACIAAACIAAADQAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIADgDQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAIADABIAAgDIABAAIgBgEIABAAIABgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBIABAAIAAABIAAAEIAAADIAAADIAAADIgDAOQgDAQgKALQgDAAgDACIgDgCg");
	this.shape_31.setTransform(3.7,-1.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("rgba(21,45,79,0.996)").s().p("AAXBNQAEgDAEgCIAAgCIgCgBIgBAAIAAgBIgCAAIgDgBIgCAAQAAAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIgBgBIAAgBQAAgDgDgBIgCAAIAAgCQgEgCgDgDIAAgBIgBAAIgDgCIgBgBIgBAAIgBgBIgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIgBgBIgDgBIgCAAIgEABIgDADIgBABIgCACIgEAAIAAACIgBABIAAACQAEAGACAHIABABIgBACIgBAAIAAABIgBAAIAAACIgDgCQgNgFgLgJQgKgLgHgNQgHgNgBgSIAAgGIAAgCIAAgDQADgQAGgOQAIgNALgJQAJgIAMgGIADgBQALgDAMgCIAIAAIADAAQAAABAAAAQAAAAABAAQAAAAAAAAQAAAAAAgBIAAABQABAAAAABQAAAAAAAAQAAAAAAABQAAAAAAABIgBACIgBAAIgEAAIAAACIgCAAIgBABIgCAAQgBAAAAABQgBAAAAAAQAAAAgBAAQAAABAAAAIAAADQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAAAAAQADADAEgDIAEAAIABgDQACABAEABQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAQACABAEABIAAgCIABgBIAFADIAEABIABAAQAAAAgBABQAAABABAAQAAABAAAAQABABAAAAIAFADIACAAQADAAADADIADAAQAEAEABAFIABACQgBAAAAABQAAAAAAAAQAAABAAAAQAAAAABABIADABQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAIgEAAQgBAAAAAAQAAAAAAAAQAAABAAAAQAAABABAAIAEAJIAAACQABAEADABQAAAAAAAAQABgBAAAAQAAAAABABQAAAAABAAIABAAIgEgJQAAAAABAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIABAAQAAAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABIACACIgBAHQAAABABAAQAAABAAAAQAAABAAAAQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABQAAAAAAABIABACIAAACIgEgHQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAgBIgBgBIAAACIAAACIgBAEQAAABAAAAQAAABABAAQAAABAAAAQABABAAAAIAAgDQAAAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAgBIAEAFIABgDIABAAIAAADQAAAAAAABQgBAAAAABQAAAAAAABQAAABAAAAIACADQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgBABIAAACIABABIgBAAIAAACIABADIABAAQAAAAAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIADgCIgBACIgDADIgBAGQgGAHgBANIAAAFIADACQADgCADAAIgBACQgIALgMAIQgIAFgLAEIgKADIACgDgAghgGIgBAEIAAADQAAAEgBADIgBABIAAAAIAAACIACAFIAAABIABACIAAABIABABQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIACADIADAEIAAABIADADIAAADIAAACIAAABIABAAIAAABIABAAIAAABIABACIAFACIAAgBIgBAAIgCgCIgBgCQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBIAAgBIAAAAIACgCQABgBAAAAQAAgBAAAAQAAgBAAAAQgBAAgBAAIAAgCIgBgBIgBAAIgBgCIADgDIAAgDIgCAAIgCAAIAAACIgCAAQgDgDAAgEIAAgBIABAAIAAgCIAAgBIABAAIADgCIACAAIABAAIABAAIAEADIABAAIAFAEIAAABIAAACIAAADQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBIAAgCIABgBIACgCQAAgBAAAAQAAAAABAAQAAAAAAAAQABAAAAABIAEgBIABgCIAAgBIABgBIADgBIACgCIACAAIABgBQABgBAAAAQABAAAAAAQABAAAAABQABAAAAABIABAAIAFgBIABAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBAAIgBgBIgBgBQAAgBAAAAQAAgBAAAAQgBAAAAAAQgBgBAAAAIgCAAIAFgBIABAAQAAABAAAAQAAAAABAAQAAAAAAAAQAAAAABAAIACAAIAAgBIABAAQAAAAAAgBQABAAAAgBQAAAAgBgBQAAAAAAgBIAAgCIgBgBIAAgBQgBgCgEgCIAAgDQgBgCgDgBIgBABIAAACIgCABIAAACIgBABIAAABIgBAAIgCAEIAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAAAgBIgBgBIAAgBQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIgBgBIAAgBIABAAQABAAAAgBQAAAAAAAAQABAAAAgBQAAAAAAgBIACgBQAAAAAAAAQAAAAAAAAQABAAAAAAQABgBAAAAIAHgBIAAgBIAAgBIAAgBIgCAAIgBgBIABgDIAAgBIgBgBIAAABIgCABQAAABgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBIAAgBIABgBIAAgBQABgBAAAAQAAgBAAAAQAAAAAAAAQAAAAgBAAIgBgEQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgCAAIAAACIABAAQAAABgBAAQAAABAAAAQAAABAAAAQABAAAAABIAAACIgBAAQgDgEgBgEIgBgBIAAgBIAAgCIAAgEIABgCIAAgBIgCgDIgBAAIgCgBIgBAAIgCABIgDgBIgBAAIgCABIgCACQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAABAAAAQAAABAAAAQABABAAAAQABAAAAABIACAEIAAAFIgBAAIAAABIgBABIgGAFIAAABIgBACIgBACIgBAAIAAABIAAACQgHACgEAFIAAACIAAAAIgEAEIAAABIgBABIAAACIgBAFIAAABIgBAEIABADQAAABAAAAQAAAAABAAQAAAAAAgBQAAAAAAgBIgBAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAgBAAAAIAAgDIACgCIAAAAgAgDAkQABAEAEAAIAAgBIgBgBQAAAAAAgBQAAAAgBgBQAAAAAAAAQAAAAAAAAIgCgBIgBABgAgGAiIADABQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBAAAAgBIgDgCQgBgCgEgBQAEADADAFgAAcABIAAAHIADABIgCgIIAAgBIgBABgAAqgJQgDgBAAgEIADgDQABgDADAAIABgDIgBgDIgBgDIgEgHIAAgBIgGgDIAAACIgCAAQgBAAAAgBQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAgBAAQAAAAgBAAIgCAAQAAABgBAAQAAABgBAAQAAABgBAAQAAAAgBABIAAACIADACQAAAAAAgBQABAAAAgBQABAAAAAAQABgBAAAAIABAAQgBADABACIAFAJIgBAAIgBAFIABADIACAFIAGAAIAAAAgAAxgTQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAQAAABAAAAQAAABABAAQAAABAAAAQAAAAABAAIAEgBQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIAAgCIgBAAIgCgBIgCABgAAZgPIACgBQAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAAgCIgBgEIAAgBIAAgCIgBgBIgBgEQgDgCgCAAQAAABgBAAQAAABAAAAQAAABAAAAQABAAAAABIADAEIgBAFIgBAAIgCAAIAGAFg");
	this.shape_32.setTransform(-0.6,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.earth, new cjs.Rectangle(-8,-8,16,16), null);


// stage content:
(lib._06Start2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// earth
	this.instance = new lib.earth();
	this.instance.parent = this;
	this.instance.setTransform(397,89.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({guide:{path:[396.9,89.2,394.7,87.4,392.1,85.6,387.5,82.7,381.8,79.8,352.5,65.2,311.1,65.2,269.7,65.2,240.4,79.8,211.1,94.3,211.1,115.1,211.1,135.8,240.4,150.4,269.7,165.1,311.1,165.1,352.5,165.1,381.8,150.4,397.4,142.6,404.7,133.2,411.1,124.8,411.1,115.1,411.1,109.9,409.3,105.2,408.6,103.2,407.5,101.3,405.7,98,403,95,402.2,94,401.2,93.1,400.8,92.6,400.4,92.3,400.2,92,399.9,91.8,399.5,91.4,399.1,91]}},47).to({guide:{path:[399.1,91,399.5,91.4,399.9,91.8,400.2,92,400.4,92.3,400.8,92.6,401.2,93.1,402.2,94,403,95,405.7,98,407.5,101.3,408.6,103.2,409.3,105.2,411.1,109.9,411.1,115.1,411.1,124.8,404.7,133.2,397.4,142.6,381.8,150.4,352.5,165.1,311.1,165.1,269.7,165.1,240.4,150.4,211.1,135.8,211.1,115.1,211.1,94.3,240.4,79.8,269.7,65.2,311.1,65.2,352.5,65.2,381.8,79.8,387.5,82.7,392.1,85.6,394.8,87.4,397.1,89.3]}},1).to({guide:{path:[397.1,89.3,394.8,87.4,392.1,85.6,387.5,82.7,381.8,79.8,352.5,65.2,311.1,65.2,269.7,65.2,240.4,79.8,211.1,94.3,211.1,115.1,211.1,135.8,240.4,150.4,269.7,165.1,311.1,165.1,352.5,165.1,381.8,150.4,397.4,142.6,404.7,133.2,411.1,124.8,411.1,115.1,411.1,109.9,409.3,105.2,408.6,103.2,407.5,101.3,405.7,98,403,95,402.2,94,401.2,93.1,400.8,92.6,400.4,92.3,400.2,92,399.9,91.8,399.5,91.4,399.1,91]}},47).to({guide:{path:[399.1,91,399.5,91.4,399.9,91.8,400.2,92,400.4,92.3,400.8,92.6,401.2,93.1,402.2,94,403,95,405.7,98,407.5,101.3,408.6,103.2,409.3,105.2,411.1,109.9,411.1,115.1,411.1,124.8,404.7,133.2,397.4,142.6,381.8,150.4,352.5,165.1,311.1,165.1,269.7,165.1,240.4,150.4,211.1,135.8,211.1,115.1,211.1,94.3,240.4,79.8,269.7,65.2,311.1,65.2,352.5,65.2,381.8,79.8,387.5,82.7,392.1,85.6,394.8,87.4,397.1,89.3]}},1).to({guide:{path:[397.1,89.3,394.8,87.4,392.1,85.6,387.5,82.7,381.8,79.8,352.5,65.2,311.1,65.2,269.7,65.2,240.4,79.8,211.1,94.3,211.1,115.1,211.1,135.8,240.4,150.4,269.7,165.1,311.1,165.1,352.5,165.1,381.8,150.4,397.4,142.6,404.7,133.2,411.1,124.8,411.1,115.1,411.1,109.9,409.3,105.2,408.6,103.2,407.5,101.3,405.7,98,403,95,402.2,94,401.2,93.1,400.8,92.6,400.4,92.3,400.2,92,399.9,91.8,399.5,91.4,399,91]}},47).to({guide:{path:[399,91,399.5,91.4,399.9,91.8,400.2,92,400.4,92.3,400.8,92.6,401.2,93.1,402.2,94,403,95,405.7,98,407.5,101.3,408.6,103.2,409.3,105.2,411.1,109.9,411.1,115.1,411.1,124.8,404.7,133.2,397.4,142.6,381.8,150.4,352.5,165.1,311.1,165.1,269.7,165.1,240.4,150.4,211.1,135.8,211.1,115.1,211.1,94.3,240.4,79.8,269.7,65.2,311.1,65.2,352.5,65.2,381.8,79.8,387.5,82.7,392.1,85.6,394.8,87.4,397.1,89.3]}},1).to({guide:{path:[397.1,89.3,394.8,87.4,392.1,85.6,387.5,82.7,381.8,79.8,352.5,65.2,311.1,65.2,269.7,65.2,240.4,79.8,211.1,94.3,211.1,115.1,211.1,135.8,240.4,150.4,269.7,165.1,311.1,165.1,352.5,165.1,381.8,150.4,397.4,142.6,404.7,133.2,411.1,124.8,411.1,115.1,411.1,109.9,409.3,105.2,408.6,103.2,407.5,101.3,405.7,98,403,95,402.2,94,401.2,93.1,400.8,92.6,400.4,92.3,400.2,92,399.9,91.8,399.5,91.4,399,91]}},47).wait(1));

	// satellite
	this.instance_1 = new lib.juno();
	this.instance_1.parent = this;
	this.instance_1.setTransform(396.6,74.3,0.082,0.082,30,0,0,0.8,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({guide:{path:[396.5,74.3,395.8,73.7,395,73.2,392.1,71.1,388.9,69.1,372,58.6,350.3,54.1,334,50.7,315,50.7,270.8,50.7,237.8,69.1,204.9,87.5,202.6,113.5,200.2,139.5,229.7,157.9,259.4,176.2,303.6,176.2,347.9,176.2,380.8,157.9,413.8,139.5,416.2,113.5,418.1,91.7,399.3,74.8,362.7,44,293.7,44.3,224.8,44.5,171.4,93.4,117.9,142.2,110.5,211.3,103.2,280.5,166.9,318.8]}},191).wait(1));

	// sun
	this.instance_2 = new lib.sun();
	this.instance_2.parent = this;
	this.instance_2.setTransform(315.6,111.7,1.784,1.784,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(192));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(572.5,264.5,107.5,65.3);
// library properties:
lib.properties = {
	id: '3DB4D32FDB8D4ADBA537154B0AD56A26',
	width: 550,
	height: 400,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['3DB4D32FDB8D4ADBA537154B0AD56A26'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;